# Generated by Django 3.2.7 on 2021-10-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_eye', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='host',
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='application',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
