# Generated by Django 3.2.7 on 2021-10-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_eye', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(choices=[('submit', 'Submit'), ('pageview', 'Pageview'), ('cta click', 'CTA Click')], max_length=10),
        ),
    ]
