# Generated by Django 3.2.7 on 2021-10-11 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_eye', '0002_alter_event_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
